version: "3.0"
volumes:
    postgres:
services:
  db:
    container_name: "db-scraping"
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=postgres
      - POSTGRES_DB=general
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge

